version: "3.9"

services:
  mysql:
    image: mysql:8.0.33
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    container_name: liberfly_mysql
    restart: always
    tty: true
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - "3008"
    environment:
      - MYSQL_DATABASE=liberflydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3008
    networks:
      - liberflynet

  laravel:
    build: .
    # image: nanem/liberfly-api
    container_name: liberfly_laravel
    command: bash -c "cp .env.example .env && composer install && php artisan jwt:secret --force && php artisan l5-swagger:generate && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3008
      - DB_DATABASE=liberflydb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/app
    networks:
      - liberflynet
    depends_on:
      - mysql

networks:
  liberflynet:
